name: Playwright Tests Dispatch
on:
  repository_dispatch:
    types: [ado-event]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: self-hosted
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.44.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.104
      - run: dotnet build
      - name: Run your tests
        run: dotnet test